# Saving and loading workflows

In [1]:
from napari_workflows import Workflow
from napari_workflows._io_yaml_v1 import load_workflow, save_workflow

from skimage.io import imread, imshow
from skimage.filters import gaussian
import numpy as np

For testing purposes, we setup a simple workflow and set an input image.

In [2]:
w = Workflow()

# define denoising
w.set("denoised", gaussian, "input", sigma=2)

w.set("input", np.random.random((3, 3)))

print(str(w))

Workflow:
denoised <- (<function gaussian at 0x7fbeee604c10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[0.47154877 0.52238515 0.09982908]
 [0.13225936 0.99151751 0.19470893]
 [0.797373   0.63175369 0.62158821]]



Next, we save the workflow to disk.

In [3]:
filename = "test.yaml"

save_workflow(filename, w)

After loading the workflow, we notice that it does not contain any image data. It only consists of processing steps.

In [4]:
new_w = load_workflow(filename)
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x7fbeee604c10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)



Hence, we need to set an input image again. This image can have a different shape, but it is recommended that the input image has the same dimensionality as in the workflow before.

In [5]:
new_w.set("input", np.random.random((5,5)))
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x7fbeee604c10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[0.55271555 0.1865473  0.32010651 0.66216249 0.12470335]
 [0.71399758 0.1789046  0.75515832 0.64266356 0.42995184]
 [0.45302134 0.60495946 0.35803792 0.47418399 0.76247791]
 [0.98145038 0.02422049 0.31215555 0.29119621 0.23933155]
 [0.78526891 0.59105168 0.10690843 0.34604959 0.96627981]]



The workflow is now properly configured and we can retrieve a result image.

In [6]:
new_w.get("denoised")

/Users/haase/opt/anaconda3/envs/bio_39/lib/python3.9/site-packages/dask/core.py:119: FutureWarning: Providing the `multichannel` argument positionally to gaussian is deprecated. Use the `channel_axis` kwarg instead.
  return func(*(_execute_task(a, cache) for a in args))


array([[0.50340422, 0.4626823 , 0.42836097, 0.39867158, 0.36915657],
       [0.53325458, 0.48964026, 0.45735994, 0.43793341, 0.42566571],
       [0.56552062, 0.51600805, 0.48427072, 0.47634504, 0.48486018],
       [0.59559089, 0.53953098, 0.50831082, 0.51286339, 0.54381525],
       [0.6193631 , 0.55932612, 0.53057259, 0.54824063, 0.60091298]])