# Saving and loading workflows

In [1]:
from napari_workflows import Workflow, load_workflow, save_workflow

from skimage.io import imread, imshow
from skimage.filters import gaussian
import numpy as np

For testing purposes, we setup a simple workflow and set an input image.

In [2]:
w = Workflow()

# define denoising
w.set("denoised", gaussian, "input", sigma=2)

w.set("input", np.random.random((3, 3)))

print(str(w))

Workflow:
denoised <- (<function gaussian at 0x7fcbce30bc10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[0.48497637 0.75816051 0.14031573]
 [0.34603946 0.08406556 0.13692243]
 [0.23577745 0.69880553 0.00879575]]



Next, we save the workflow to disk.

In [3]:
filename = "test.yaml"

save_workflow(w, filename)

After loading the workflow, we notice that it does not contain any image data. It only consists of processing steps.

In [4]:
new_w = load_workflow(filename)
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x7fcbce30bc10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)



Hence, we need to set an input image again. This image can have a different shape, but it is recommended that the input image has the same dimensionality as in the workflow before.

In [5]:
new_w.set("input", np.random.random((5,5)))
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x7fcbce30bc10>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[0.59178156 0.6846652  0.43519637 0.30268906 0.34145311]
 [0.2997474  0.02844134 0.69386829 0.27804536 0.85011769]
 [0.4599325  0.61319808 0.78895489 0.20717397 0.07853446]
 [0.96491987 0.76593271 0.14202505 0.45927141 0.2099993 ]
 [0.46980968 0.72966678 0.66751213 0.06407744 0.72596583]]



The workflow is now properly configured and we can retrieve a result image.

In [6]:
new_w.get("denoised")

/Users/haase/opt/anaconda3/envs/bio_39/lib/python3.9/site-packages/dask/core.py:119: FutureWarning: Providing the `multichannel` argument positionally to gaussian is deprecated. Use the `channel_axis` kwarg instead.
  return func(*(_execute_task(a, cache) for a in args))


array([[0.52245413, 0.49796724, 0.46585394, 0.43489641, 0.41363491],
       [0.5224415 , 0.49947433, 0.46950558, 0.44109882, 0.42251875],
       [0.53343513, 0.51004154, 0.47953157, 0.45155594, 0.4349907 ],
       [0.54646837, 0.52435536, 0.49512677, 0.47019528, 0.45924778],
       [0.55122374, 0.53490747, 0.51214716, 0.49577729, 0.49583048]])