In [2]:
from napari_workflows import Workflow

from skimage.io import imread, imshow
from skimage.filters import gaussian

w = Workflow()

# define denoising
w.set("denoised", gaussian, "input", sigma=2)

w.set("input", imread('C:/Users/ryans/Desktop/blobs.tif'))

print(str(w))

Workflow:
denoised <- (<function gaussian at 0x000002686C6AF370>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[ 40  32  24 ... 216 200 200]
 [ 56  40  24 ... 232 216 216]
 [ 64  48  24 ... 240 232 232]
 ...
 [ 72  80  80 ...  48  48  48]
 [ 80  80  80 ...  48  48  48]
 [ 96  88  80 ...  48  48  48]]



In [5]:
def save_workflow(workflow, filename):
    from yaml import dump
    with open(filename + '.yaml', 'w') as stream:
        dump(workflow,stream)

name = 'C:/Users/ryans/Desktop/workflow'
save_workflow(w,name)

In [6]:
def load_workflow(filename):
    from yaml import unsafe_load
    with open(filename, "rb") as stream:
        return unsafe_load(stream)
    
new_w = load_workflow(name + '.yaml')
print(new_w)

Workflow:
denoised <- (<function gaussian at 0x000002686C6AF370>, 'input', 2, None, 'nearest', 0, None, False, 4.0)
input <- [[ 40  32  24 ... 216 200 200]
 [ 56  40  24 ... 232 216 216]
 [ 64  48  24 ... 240 232 232]
 ...
 [ 72  80  80 ...  48  48  48]
 [ 80  80  80 ...  48  48  48]
 [ 96  88  80 ...  48  48  48]]

